Add HTML text formatting option
jdepoix/youtube-transcript-api pull request #192
Opened 2023-03-16 01:37 UTC by eseiver

Decided to address #191 myself! This changes `_TranscriptParser()` to have a `preserve_formatting` option that defaults to `False`. I then added the ability to set this parameter at the user level in `YouTubeTranscriptApi.get_transcript()`, making changes to the intermediary classes and methods where appropriate. Finally, I updated the testing XML asset in [transcript.xml.static](https://github.com/eseiver/youtube-transcript-api/blob/html_formatting/youtube_transcript_api/test/assets/transcript.xml.static) to include escaped italics, as well as adding a new test `test_get_transcript_formatted()` that keeps the italics. None of the other similar tests were changed because it still defaults to the old version.

2023-04-11 13:09 UTC, jdepoix requested changes
Hi @eseiver,
thank you very much for your contribution!!! 🥳 👍 

Sorry that it took so long, but I just didn't get around to having a look at it.

There's only a few minor things and then it should be good to be merged.

2023-04-11 13:09 UTC, jdepoix commented on youtube_transcript_api/_api.py
> +    def get_transcript(cls, video_id, languages=('en',), proxies=None, cookies=None, preserve_formatting=False):
Please add `preserve_formatting` to the docstrings

2023-04-11 13:09 UTC, jdepoix commented on youtube_transcript_api/_api.py
>      def get_transcripts(cls, video_ids, languages=('en',), continue_after_error=False, proxies=None, cookies=None):
`preserve_formatting` should also be added to `get_transcripts`

2023-04-12 21:31 UTC, eseiver commented
Thanks so much for this helpful review! I have addressed all the points in some additional commits and updated a few more tests. Let me know if there's anything else needed.

2023-04-13 10:04 UTC, jdepoix requested changes
Hi @eseiver,
thank you very much for taking the time to implement the requested changes. Unfortunately, I just now realized that we don't need to hold the state for `preserve_formatting` in that many places, as it does not become relevant until the actual transcript is fetched. However, implementing that change should mainly require deleting code and should actually make the code simpler 👍

2023-04-13 10:04 UTC, jdepoix commented on youtube_transcript_api/_transcripts.py
> +        self.preserve_formatting = preserve_formatting
We do not need to keep this state around, since it is not needed after the object has been initialized

2023-04-13 10:07 UTC, jdepoix commented
Somehow the builds haven't run yet, I will have a look into that!

2023-04-13 19:58 UTC, eseiver commented
Alright that makes sense that `preserve_formatting` can be mostly in class methods not in `__init__`. Updated and also moved `_FORMATTING_TAGS` into `_TranscriptParser`.

2023-04-17 13:15 UTC, jdepoix commented
Hi @eseiver, thanks for the additional fixes! I just added a few of the missing things myself. I will merge this now and release it with v0.6.0 🥳

2023-04-17 13:15 UTC, merged

2023-04-17 13:53 UTC, jdepoix commented
I just release this in [v0.6.0](https://github.com/jdepoix/youtube-transcript-api/releases/tag/v0.6.0). Thank you for your contribution! 😊 🙏