Feature/issue 213
jdepoix/youtube-transcript-api pull request #219
Opened 2023-07-27 05:06 UTC by crhowell

Updates `_extract_captions_json` method to do additional html splitting to attempt to extract out the `playabilityStatus` JSON object so we may match and raise a more specific error against the "status" field.
Updates `CouldNotRetrieveTranscript` class to accept `playabilityStatus` JSON object so we can generate more informative errors with cause, reason, subreason attached.

2023-10-31 18:57 UTC, ilystsov requested changes
Remove redundant checks, simplify the code

2023-10-31 18:57 UTC, ilystsov commented on youtube_transcript_api/_errors.py
> +    return ""
```suggestion
    error_screen = playability_json.get("errorScreen", {})
    renderer = error_screen.get("playerErrorMessageRenderer", {})
    subreason = renderer.get("subreason", {}).get("runs", [])

    if subreason:
        return subreason[0].get('text', '')

    return ""
```

2024-09-23 20:58 UTC, AndreCAndersen commented on youtube_transcript_api/_errors.py
> +        # error for age related playability
`LOGIN_REQUIRED` also happens when you need to "Sign in to confirm you’re not a bot". This simpler pull request addresses this: https://github.com/jdepoix/youtube-transcript-api/pull/337

2025-03-11 20:54 UTC, jdepoix commented
Hi @crhowell !

I am so sorry for taking so long to make any progress on this, but I didn't want to merge this without putting more time into testing it out and finding different edge cases! 🙈 

I have finally gotten around to putting some time into it and have now refactored how the errors are parsed, which has allowed me to add a few new exception types, that should make quite a few error cases a lot more explicit! I have released this as part of [v1.0.0](https://github.com/jdepoix/youtube-transcript-api/releases/tag/v1.0.0). Since I have refactored some interfaces as part of this release I unfortunately I wasn't able to directly merge your code. But although I will have close this PR without merging it, I thank you very much for your contribution, as it was a very helpful resource while refactoring the error parsing! 😊🙏

2025-03-11 20:54 UTC, closed without merging

2025-03-14 17:54 UTC, crhowell commented
> Hi @crhowell !
> 
> I am so sorry for taking so long to make any progress on this, but I didn't want to merge this without putting more time into testing it out and finding different edge cases! 🙈
> 
> I have finally gotten around to putting some time into it and have now refactored how the errors are parsed, which has allowed me to add a few new exception types, that should make quite a few error cases a lot more explicit! I have released this as part of [v1.0.0](https://github.com/jdepoix/youtube-transcript-api/releases/tag/v1.0.0). Since I have refactored some interfaces as part of this release I unfortunately I wasn't able to directly merge your code. But although I will have close this PR without merging it, I thank you very much for your contribution, as it was a very helpful resource while refactoring the error parsing! 😊🙏

@jdepoix  No worries at all, glad you were able to find time to work in a refactor. My work has kept me fairly busy and working quite a lot in Golang the past few years. I do miss Python from time to time but Golang is great too, love the tooling.