This is a workaround to avoid IP Ban by YouTube and to solve the issue #303
jdepoix/youtube-transcript-api pull request #312
Opened 2024-08-07 14:10 UTC by danielsanmartin

To fetch HTTPS pages, you will need to download and install the a certificate in your HTTP client. In this case, we need to pass to requests the verify paramenter which sets the path to certificate.

2024-08-07 16:37 UTC, 0xRaduan commented
very useful, @danielsanmartin - do you have some sort of a walkthrough, on how exactly I need to install those ca certificates and specify them here?

2024-08-08 09:18 UTC, jdepoix requested changes
Hi @danielsanmartin 👋 
Thank you very much for your contribution! 😊 

Just to make sure I am not missing something: this just allows you to specify/override the CA certificate used, which is required by Zyte to use their https proxies. This might potentially also be the case for other proxy services, but it is fairly provider specific. Correct?

I am happy to merge this (with some slight adjustments mentioned in the comments), I just want to make very clear that this **does not solve** #303 and **it does not avoid IP bans**, it only allows you to use Zyte as a workaround to being IP banned, but even your proxies IP can still be banned in the future by YouTube. (I just want to highlight this, as the title of this PR might raise some false expectations and a lot of people are currently following #303)

2024-08-08 09:18 UTC, jdepoix commented on youtube_transcript_api/_api.py
> +            http_client.verify = verify if verify else {}
`verify` can also be a boolean so this condition can have unintended side-effects when `verify` is set to `False`. Also, it should not be set to `{}` in any case under any circumstances.
Just do this instead
```python
if verify is not None:
    http_client.verify = verify
```

2024-08-08 09:18 UTC, jdepoix commented on youtube_transcript_api/_api.py
> +        :type verify: str
can be a boolean

2024-08-08 09:18 UTC, jdepoix commented on youtube_transcript_api/_api.py
> +        :param verify: the path to a CA_BUNDLE file or directory with certificates of trusted CAs
Probably best to link to [the official requests docs here](https://docs.python-requests.org/en/latest/user/advanced/#ssl-cert-verification) as done for `proxies`.

2024-08-08 09:18 UTC, jdepoix commented on youtube_transcript_api/_api.py
> +        :type verify: str
same here

2024-08-08 09:18 UTC, jdepoix commented on youtube_transcript_api/_api.py
> +        :type verify: str
same here

2024-08-08 09:41 UTC, jdepoix commented
Also, it would be great if you could mention this param in the README. I think you can just add it to the Proxy section.

2024-08-08 11:47 UTC, danielsanmartin commented on youtube_transcript_api/_api.py
> +        :type verify: str
Perfect!

2024-08-08 11:50 UTC, danielsanmartin reviewed
Perfect. I agree with all the proposed developments.

2024-08-10 23:08 UTC, danielsanmartin commented
Hi. I already did the requested changes.

2024-08-15 03:09 UTC, danielsanmartin reviewed
All requested changes were done.

2025-03-11 19:01 UTC, jdepoix commented
Hi @danielsanmartin!

sorry that it took so long, but I was hesitant merge this, as I had some larger-scale changes to the API in mind, which I just got around to releasing in [v1.0.0](https://github.com/jdepoix/youtube-transcript-api/releases/tag/v1.0.0)!

In this new version an instance of `YouTubeTranscriptApi` can be initialized with a `requests.Session` object. This allows for specifying the CA bundle file, but at the same time allows for doing other things like settings custom headers!

```python
from requests import Session

http_client = Session()

# set custom header
http_client.headers.update({"Accept-Encoding": "gzip, deflate"})

# set path to CA_BUNDLE file
http_client.verify = "/path/to/certfile"

ytt_api = YouTubeTranscriptApi(http_client=session)
ytt_api.fetch(video_id)

# share same Session between two instances of YouTubeTranscriptApi
ytt_api_2 = YouTubeTranscriptApi(http_client=session)
# now shares cookies with ytt_api
ytt_api_2.fetch(video_id)
```

Since this new API allows for setting CA bundles without requiring an extra param for it, I will close this PR now. Nonetheless, thank you very much for your contribution @danielsanmartin! 😊🙏

2025-03-11 19:01 UTC, closed without merging